### ISSUE TITLE
Feature Request: Adding Support for TOML files

### ISSUE THREAD

**Issue by Pasqua101** [Vishnudas2003/Text2Page#3]
Hi @Vishnudas2003, I would like to add a feature to your project that allows for the support of parsing TOML files. I would like to add this option to allow for the user to specify their command line arguments in the TOML  instead of having to pass it to the command line all the time.  The feature can used by either typing `-c` or `--config` into the command line, and can be executed like so `python text2page.py ./file.txt -c ./config.toml`. I will be trying to attempt this by using the [tomllib](https://docs.python.org/3.11/library/tomllib.html) library to assist me. Please let me know what you think. You can also reach out to me on Slack, I'm Marco Pasqua.

**Comment by humphd** [comment]
Looks like this was landed in https://github.com/Vishnudas2003/Text2Page/pull/4.
